server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gdp?serverTimezone=UTC
    username: root
    password: 123456
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm
    #    date-format: yyyy-MM-dd HH:mm
  mail:
    host: smtp.qq.com
    port: 587
    username: 1600677562@qq.com
    password: bzlbyskdmadkidjf
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true


mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml
  type-aliases-package: org.t01.gdp.domain

time:
  cron-for-time-axis: 0 */1 * * * *
  cron-for-clear-verifivation-code: 0 */6 * * * *

mail:
  from: ${spring.mail.username}
logging:
  level:
    org.t01.gdp.mapper: debug